version: '3'
   
services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: container
    volumes:
      - .:/cointainer
    ports:
      - "8000:8000"
  stream:
    build: .
    command: bash -c "pip3 install websockets && python3 TweetBook/streamsearch.py"
    depends_on:
      - web
    ports:
      - "5000:5000"